### ISSUE TITLE
Data problem

### ISSUE THREAD

**Issue by LucasPages** [zmd971202/OpenNER#1]
Hi, I just looked at the AnchorNER data you published on Google Drive (in the data folder of the github) and I noticed an annotation error on line 901 of the AA.txt. The tag for this token is "I-MISC" despite the iob tag at line 900 being "O".
Similar errors exist on lines 1014 and 1966.

Is this a known issue ? Should it be considered part of the corpus ?

Thank you.

**Comment by zmd971202** [comment]
Hi, there may be some errors in the data as the annotations are the outputs of our correction model. It is not a manually-annotated dataset.

**Comment by LucasPages** [comment]
Thank you for the clarification !
